format = """
$directory\
$git_branch\
$git_status\
$character"""

[directory]
style = "bright-black"
truncation_length = 3
truncate_to_repo = true

[character]
success_symbol = "[\\$](green)"
error_symbol = "[\\$](red)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "purple"

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "yellow"
modified = "~"
staged = "+"
untracked = "?"
deleted = "x"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
